from enum import Enum


class ServiceStatus(Enum):
    SUCCESS='SUCCESS'
    FAILURE='FAILURE'


class APIStatus(Enum):
    START='START'
    SUCCESS='SUCCESS'
    FAILURE='FAILURE'


class SystemStatus(Enum):
    ONLINE='ONLINE'


class BackupStatus(Enum):
    ENABLED='ENABLED'
    DISABLED='DISABLED'


class TableStatus(Enum):
    CREATING='CREATING'
    UPDATING='UPDATING'
    DELETING='DELETING'
    ACTIVE='ACTIVE'
    INACCESSIBLE_ENCRYPTION_CREDENTIALS='INACCESSIBLE_ENCRYPTION_CREDENTIALS'
    ARCHIVING='ARCHIVING'
    ARCHIVED='ARCHIVED'


class AlarmStatus(Enum):
    OK='OK'
    ALARM='ALARM'
    INSUFFICIENT_DATA='INSUFFICIENT_DATA'


class IndexStatus(Enum):
    CREATING='CREATING'
    UPDATING='UPDATING'
    DELETING='DELETING'
    ACTIVE='ACTIVE'
